### PR TITLE
feat: post_playlist and delete_playlist method

### PR DESCRIPTION
**Pull request by bretheskevin**

### CODE REVIEW

**Comment by 7x11x13** [comment]
Can you add delete playlist as well so the test can clean itself up?

**Comment by bretheskevin** [comment]
> Can you add delete playlist as well so the test can clean itself up?

Done :)

**Comment by 7x11x13** [comment]
We should also add the playlist PUT method so we can edit playlists once they have been created. But that will be another PR

**Comment by bretheskevin** [comment]
Yep, I’ll add it

---
Sent with Gmail for Sidekick Browser

**Pull request merged**
