### PR TITLE
API For Listening History

### PR DESCRIPTION
**Pull request by CosmicSage**
Hello Morderator

Thank you for writing this wrapper.

This wrapper is used by scdl and that's how I found this porject.

Ok so you know that Scound cloud doesn;t  give endpoint for listening history, though it can be obtained as (well maybe I shoulfd use that s word it is so offensive so 'obtained') the domain for history is just the same as other API stuff.

I have tried my best to write non-invasive code and keep +diffs to a minimum and this is the result. I hope you like it

The response from history endpoint returns non standard response to the rest of the stuff so I used 1 If statement and addede a new datastructer

Feel free to change names and also read comments in the files.

I hope you like it!!! Please merge!

### CODE REVIEW

**Comment by CosmicSage** [comment]
Screenshot (468)

Morderator heres an example response from scoundloud history point

Limit is powerfull paylod makes it convenient

**Comment by CosmicSage** [comment]
Please merge fast this has implications for scdl. I'm writing new feature there @7x11x13

**Comment by CosmicSage** [comment]
The mod is absolute cuck

**Comment by 7x11x13** [comment]
Listening history is now available in v1.3.8

**Pull request closed without merging**
